name: win32-sdrpp-plugin
on: workflow_dispatch
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
        with:
          repo: 'cropinghigh/sdrpp-vhfvoiceradio'

      - name: Create Build Environment
        run: dir ; cmake -E make_directory build ; dir

      - name: Download PothosSDR
        run: Invoke-WebRequest -Uri "https://downloads.myriadrf.org/builds/PothosSDR/PothosSDR-2020.01.26-vc14-x64.exe" -OutFile ${{runner.workspace}}/pothos.exe
      - name: Install PothosSDR
        run: mkdir "C:/Program Files/PothosSDR" ; 7z x ${{runner.workspace}}/pothos.exe -o"C:/Program Files/PothosSDR/"

      - name: Download libusb
        run: Invoke-WebRequest -Uri "https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.7z" -OutFile ${{runner.workspace}}/libusb.7z
      - name: Patch Pothos with earlier libusb version
        working-directory: ${{runner.workspace}}
        run: dir ; 7z x libusb.7z -olibusb_old ; rm "C:/Program Files/PothosSDR/bin/libusb-1.0.dll" ; cp "libusb_old/MS64/dll/libusb-1.0.dll" "C:/Program Files/PothosSDR/bin/" ; rm "C:/Program Files/PothosSDR/lib/libusb-1.0.lib" ; cp "libusb_old/MS64/dll/libusb-1.0.lib" "C:/Program Files/PothosSDR/lib/" ; dir

      - name: Get SDR++ master source
        run: Invoke-WebRequest -Uri "https://github.com/AlexandreRouma/SDRPlusPlus/archive/refs/heads/master.zip" -OutFile master.zip ; dir

      - name: Get SDR++ nightly lib
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'AlexandreRouma/SDRPlusPlus'
          version: 'tags/nightly'
          file: 'sdrpp_windows_x64.zip'

      - name: Unpack SDR++ source and core lib
        run: mkdir sdrpp_lib ; 7z x master.zip -osdrpp_lib ; 7z x sdrpp_windows_x64.zip -osdrpp_lib ; cp .github/workflows/sdrpp_module_hack.cmake ./ ; dir

      - name: Prepare MinGW
        run: C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "pacman --noconfirm -S --needed base-devel mingw-w64-x86_64-binutils mingw-w64-x86_64-tools"
      - name: Generate .def file
        working-directory: sdrpp_lib/sdrpp_windows_x64
        run: C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "gendef sdrpp_core.dll"
      - name: Generate .lib file
        working-directory: sdrpp_lib/sdrpp_windows_x64
        run: C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -c "dlltool -d sdrpp_core.def -l sdrpp_core.lib"

      - name: Install vcpkg dependencies
        run: vcpkg install fftw3:x64-windows glfw3:x64-windows portaudio:x64-windows zstd:x64-windows libusb:x64-windows
      - name: Prepare CMake
      working-directory: build
        run: cmake "$Env:GITHUB_WORKSPACE" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DSDRPP_CORE_ROOT="$Env:GITHUB_WORKSPACE/sdrpp_lib/SDRPlusPlus-master/core" -DSDRPP_LIB_ROOT="$Env:GITHUB_WORKSPACE/sdrpp_lib/sdrpp_windows_x64" -DSDRPP_MODULE_CMAKE="$Env:GITHUB_WORKSPACE/sdrpp_module_hack.cmake" -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: Build
        working-directory: build
        run: cmake --build . --config RelWithDebInfo --verbose ; dir
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
            name: vhfvoiceradio_win
            path: build/RelWithDebInfo/*.dll
      - name: Upload pdb
        uses: actions/upload-artifact@v4
        with:
            name: vhfvoiceradio_win_pdb
            path: build/RelWithDebInfo/*.pdb